name = "Overseer Minecraft"
author = "Minecraft Server"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6115bbefc1fd11ee3fc39f1d0806539508d65d5328473244b1b1439b298d7165"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
