name = "Overseer Minecraft"
author = "Minecraft Server"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f7f0168bd8fa29a80cd9376129afe1add3ad2bf75428ef8ec0d7d2a54725daa"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
